In [11]:
import numpy as np

A = np.array([[3, 13, 19],
              [8, 1, 9]])

B = np.array([[2, 0, 2],
              [1, 2, 9]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[ 3 13 19]
 [ 8  1  9]]

Matrix B:
 [[2 0 2]
 [1 2 9]]


In [12]:
# Matrix Addition
C = A + B
print("\nMatrix C (A + B):\n", C)



Matrix C (A + B):
 [[ 5 13 21]
 [ 9  3 18]]


In [13]:
# Scalar Multiplication
D = 2 * A
print("\nMatrix D (2 * A):\n", D)


Matrix D (2 * A):
 [[ 6 26 38]
 [16  2 18]]


In [14]:
# Matrix Transpose
E = B.T
print("\nMatrix E (Transpose of B):\n", E)


Matrix E (Transpose of B):
 [[2 1]
 [0 2]
 [2 9]]


In [15]:
# Matrix Multiplication
F = C @ E
print("\nMatrix F (C x E):\n", F)


Matrix F (C x E):
 [[ 52 220]
 [ 54 177]]


In [16]:
# Sum of All Elements in Matrix C
sum_C = C.sum()
print("\nSum of elements in Matrix C:", sum_C)


Sum of elements in Matrix C: 69


In [17]:
# Zero Matrix (2x3)
zero_matrix = np.zeros((2, 3), dtype=int)
print("\nZero Matrix:\n", zero_matrix)


Zero Matrix:
 [[0 0 0]
 [0 0 0]]
